---
- name: add kubernetes repo
  copy:
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    dest: /etc/yum.repos.d/kubernetes.repo
  register: kubernetesrepo

- name: update yum caÑhe
  yum:
    update_cache: true
  when: kubernetesrepo.changed

- name: install kubelet, kubectl and kubeadm
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

# - name: install kubectl
#   yum:
#     name: kubectl
#     state: present
#   when: node_role == "master"

- name: enable service kubelet
  service:
    name: kubelet
    enabled: yes
  notify :
    - reboot
